### ISSUE TITLE
'gbk' codec issue

### ISSUE THREAD

**Issue by JohnnyDagger** [IaaC/IoP#1]
Traceback (most recent call last):
  File "C:/MaCT_DataAna/IoP/tweepy/listener.py", line 75, in <module>
    stream.filter(locations = [2.0434, 41.2510, 2.4227, 41.5030])
  File "C:\Python37\lib\site-packages\tweepy\streaming.py", line 453, in filter
    self._start(is_async)
  File "C:\Python37\lib\site-packages\tweepy\streaming.py", line 368, in _start
    self._run()
  File "C:\Python37\lib\site-packages\tweepy\streaming.py", line 300, in _run
    six.reraise(*exc_info)
  File "C:\Python37\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Python37\lib\site-packages\tweepy\streaming.py", line 269, in _run
    self._read_loop(resp)
  File "C:\Python37\lib\site-packages\tweepy\streaming.py", line 331, in _read_loop
    self._data(next_status_obj)
  File "C:\Python37\lib\site-packages\tweepy\streaming.py", line 303, in _data
    if self.listener.on_data(data) is False:
  File "C:/MaCT_DataAna/IoP/tweepy/listener.py", line 46, in on_data
    writer.write_tweet(file_path, tweet_line)
  File "C:\MaCT_DataAna\IoP\tweepy\config\writer.py", line 18, in write_tweet
    writer.writerow(tweet)
  File "C:\Python37\lib\csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'gbk' codec can't encode character '\xf1' in position 447: illegal multibyte sequence

Process finished with exit code 1

**Comment by diegopajarito** [comment]
I think this is mostly related to your OS encoding system.

**Comment by diegopajarito** [comment]
I was unable to replicate this issue. We need to check it directly in your computer.
